package com.picpick.service;

import com.picpick.dto.ChatRequest;
import com.picpick.dto.ChatResponse;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Flux;

/**
 * Service class for interacting with the AI chat model.
 * Uses Spring AI's ChatClient to send prompts and receive responses.
 */
@Service // Marks this class as a Spring-managed service bean
public class ChatService {

    /**
     * The ChatClient instance used to communicate with the AI model.
     * This client is thread-safe and can be used for multiple requests.
     */
    private final ChatClient chatClient;

    /**
     * Constructor for ChatService.
     * Spring automatically injects a ChatClient.Builder, which we use to build the
     * ChatClient.
     *
     * @param chatClientBuilder The builder provided by Spring AI's configuration.
     */
    public ChatService(ChatClient.Builder chatClientBuilder) {
        // Build the ChatClient from the provided builder
        this.chatClient = chatClientBuilder.build();
    }

    /**
     * Performs a standard, blocking chat request.
     * The thread will wait until the entire response is returned from the AI model.
     *
     * @param request The chat request containing the user's message.
     * @return A ChatResponse object with the complete AI response text.
     */
    public ChatResponse chat(ChatRequest request) {
        // Build a prompt, set the user message, call the AI model, and get the content
        String response = chatClient.prompt()
                .user(request.getMessage())
                .call()
                .content();
        return new ChatResponse(response);
    }

    /**
     * Performs a streaming chat request.
     * Returns a Flux that emits chunks of the response as they are generated by the
     * AI model.
     *
     * @param request The chat request containing the user's message.
     * @return A Flux of strings representing the streaming AI response.
     */
    public Flux<String> chatStream(ChatRequest request) {
        // Build a prompt, set the user message, and stream the content
        return chatClient.prompt()
                .user(request.getMessage())
                .stream()
                .content();
    }
}
