package com.picpick.gemini;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object for chat responses.
 * Used to return the AI-generated response back to the client.
 */
@Data // Generates getters, setters, toString, equals, and hashCode methods
@NoArgsConstructor // Generates a no-argument constructor (required for JSON deserialization)
@AllArgsConstructor // Generates a constructor with all fields
public class ChatResponse {
    /**
     * The text response generated by the AI model.
     */
    private String response;
}
